version: "3.7"

services:
  caddy:
    image: caddy:latest
    restart: always
    command: caddy file-server --root /srv --listen :80
    ports:
      - "${FILESERVER_PORT:-8080}:80"
    volumes:
      - ${FILESERVER_DATA_PATH:-./data}:/srv

  mongo:
    image: mongo
    hostname: db
    restart: always
    ports:
      - ${MONGODB_PORT:-27017}:27017
    environment:
      MONGODB_USERNAME: ${MONGODB_USERNAME:-admin}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:-password}
    volumes:
      - ${MONGODB_DATA_PATH:-./db}:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD:-password}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USERNAME:-admin}:${MONGODB_PASSWORD:-password}@mongo:27017/
